## Numpy Array Operations 

In [3]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print("Basic slicing:", arr[1:4])  # Output: [2 3 4]
print("Slicing with step:", arr[0:5:2])  # Output: [1 3 5]
print("Negative indices:", arr[:-3])  # Output: [3 4 5]

Basic slicing: [2 3 4]
Slicing with step: [1 3 5]
Negative indices: [1 2]


In [6]:
arr_2d = np.array([[1, 2, 3],   #row and column start from 0
                   [4, 5, 6], 
                   [7, 8, 9]])
print("Specific element:", arr_2d[1, 2])  # Output: 6
print("row slice:", arr_2d[0, :])  # Output: [1 2 3]
print("column slice:", arr_2d[:, 1])  # Output: [2 5 8]

Specific element: 6
row slice: [1 2 3]
column slice: [2 5 8]


 ## Sorting

In [18]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2])
sorted_arr = np.sort(unsorted)
print(sorted_arr)  # Output: [1 1 2 3 4 5 9]

arr_2d_unsorted = np.array([[3, 1, 4],
                            [1, 5, 9],  
                            [2, 6, 5]])
sorted_2d = np.sort(arr_2d_unsorted, axis=0)  # Sort each column
print("Sorted 2D array by column: \n" ,sorted_2d)

sorted_2d = np.sort(arr_2d_unsorted, axis=1)  # Sort each row   
print("Sorted 2D array by row: \n", sorted_2d)

[1 1 2 3 4 5 9]
Sorted 2D array by column: 
 [[1 1 4]
 [2 5 5]
 [3 6 9]]
Sorted 2D array by row: 
 [[1 3 4]
 [1 5 9]
 [2 5 6]]


## Filter

In [ ]:
number = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = number[number % 2 == 0]
print(even_numbers)  # Output: [ 2  4  6 

#with mask
mask = number % 2 == 0
print(number[mask])

   

[ 2  4  6  8 10]
[ 2  4  6  8 10]


## Filter With Mask

In [ ]:
mask = number > 5
 
print("Numbers greater than 5 :",number[mask])  # Output: [ 6  7  8 9 10]

Numbers greater than 5 : [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [ ]:
indices = [0, 2, 4]
print("Fancy indexing:", number[indices])  # Output: [1 3 5]


where_result = np.where(number > 5)# giving index
print(where_result)
print("np.where() result:", number[where_result])  # Output: [ 6  7  8 9 10] , giving value

Fancy indexing: [1 3 5]
(array([5, 6, 7, 8, 9]),)
np.where() result: [ 6  7  8  9 10]


In [31]:
condition_array = np.where(number > 5 , True, False)
print("Condition array:", condition_array)  

Condition array: [False False False False False  True  True  True  True  True]


## Adding and Removing data

In [35]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = arr1 + arr2
print("Combined array:", combined)  # Output: [5 7 9]

concatenated = np.concatenate((arr1, arr2))
print("Concatenated array:", concatenated)  # Output: [1 2 3 4 5 6]

Combined array: [5 7 9]
Concatenated array: [1 2 3 4 5 6]


## array compatibility

In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 
c = np.array([7, 8, 9])

print("Compatibility check a and b:", a.shape == b.shape)  # Output: True
print("Compatibility check a and c:", a.shape == c.shape)  # Output: True 

Compatibility check a and b: True
Compatibility check a and c: True


In [47]:
original = np.array([[1, 2] , [3,4]])

new_row = np.array([[5, 6]])
with_new_row = np.vstack([original, new_row])
print(original)
print("Array after adding new row:\n", with_new_row)

new_column = np.array([[7], [8], [9]])
with_new_column = np.hstack([with_new_row, new_column])
print("Array after adding new column:\n", with_new_column)

[[1 2]
 [3 4]]
Array after adding new row:
 [[1 2]
 [3 4]
 [5 6]]
Array after adding new column:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [48]:
arr = np.array([1, 2, 3])
deleted = np.delete(arr, 1)  # Remove element at index 1
print("Array after deletion:", deleted)  # Output: [1 3]

Array after deletion: [1 3]
