## Numpy array and basics
learn about Numpy with chaiaurcode

In [8]:
import numpy as np

create array from list

In [9]:
arr_1d = np.array([1,2,3,4])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array


In [15]:
py_list = [1,2,3,4]
print("Python list multiply by 2: ", py_list * 2)

np_array = np.array([1,2,3,4])#element wise multiplication
print("NumPy array multiply by 2: ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n Time taken by Python list: ", time.time() - start)

strart = time.time()
np_array = np.arange(1000000) * 2
print("\n Time taken by NumPy array: ", time.time() - start)

Python list multiply by 2:  [1, 2, 3, 4, 1, 2, 3, 4]
NumPy array multiply by 2:  [2 4 6 8]

 Time taken by Python list:  0.21927642822265625

 Time taken by NumPy array:  0.2296452522277832


### creating array from scratch 

In [20]:
zeros = np.zeros((3,4))
print("\n Array of zeros: \n", zeros)

ones = np.ones((2,3))
print("\n Array of ones: \n", ones)

full = np.full((3,3), 7)
print("\n Array of 7s: \n", full)

random = np.random.random((2,3))
print("\n Array of random numbers: \n", random)

sequence = np.arange(10, 21, 2)
print("\n Array with a sequence of numbers: \n", sequence)


 Array of zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 Array of ones: 
 [[1. 1. 1.]
 [1. 1. 1.]]

 Array of 7s: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

 Array of random numbers: 
 [[0.41004709 0.20647342 0.01288125]
 [0.14797639 0.95365676 0.52484791]]

 Array with a sequence of numbers: 
 [10 12 14 16 18 20]


### Vector, Matrix and Tensor}

In [25]:
vector = np.array([1,2,3])
print("\n Vector: \n", vector)

matrix = np.array([
                   [1,2,3],
                   [4,5,6],
                   [7,8,9] 
                   ])
print("\n Matrix: \n", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("\n Tensor: \n", tensor)


 Vector: 
 [1 2 3]

 Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [26]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape of array: ", arr.shape)
print("Dimation of array: ", arr.ndim)
print("size: ", arr.size)
print("Dtype: ", arr.dtype)

Shape of array:  (2, 3)
Dimation of array:  2
size:  6
Dtype:  int64


### Array Reshaping


In [35]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3,4))
print("Reshaped array (3x4): \n", reshaped)

flattended = reshaped.flatten()
print("Flattended array: ", flattended)

# ravel is similar to flatten but it returns a view if possible, instead of a copy
reveled = reshaped.ravel()
print("Raveled array: ", reveled)

# Transpose
transposed = reshaped.T
print("Transposed array: \n", transposed)



Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3x4): 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattended array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
